[package]
name = "blake3-js"
version = "0.1.0"
edition = "2018"

[lib]
name = "thread_count"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.9"

[dependencies]
blake3 = "1.2"
neon = "0.9"
