name: Generate Binaries
'on':
  push:
    branches:
      - generate-binary
jobs:
  build:
    name: Build
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir dist
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly
      - uses: actions/setup-node@v1
        with:
          node-version: v17.1.0
      - shell: powershell
        name: use npm 6 on node 15
        run: npm install -g npm@6
        if: matrix.os == 'windows-latest'
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: npm install neon-cli rimraf
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-102.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v16.13.0
      - shell: powershell
        name: use npm 6 on node 15
        run: npm install -g npm@6
        if: matrix.os == 'windows-latest'
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-93.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v15.14.0
      - shell: powershell
        name: use npm 6 on node 15
        run: npm install -g npm@6
        if: matrix.os == 'windows-latest'
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-88.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v14.18.1
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-83.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v13.14.0
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-79.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v12.22.7
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-72.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v11.15.0
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-67.node'
      - uses: actions/setup-node@v1
        with:
          node-version: v10.24.1
      - shell: powershell
        name: patch node-gyp for VS 2019
        run: "npm install --global node-gyp@latest\r\nnpm prefix -g | % {npm config set node_gyp \"$_\\node_modules\\node-gyp\\bin\\node-gyp.js\"}"
        if: matrix.os == 'windows-latest'
      - run: ./node_modules/.bin/rimraf rs/native/target
      - run: ../node_modules/.bin/neon build --release
        working-directory: rs
      - run: 'mv rs/native/index.node dist/${{ matrix.os }}-64.node'
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
